apiVersion: v1
kind: Service
metadata:
  labels:
    environment: dev
  name: hello-world-go-svc-dev
  namespace: go-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-world-go
    environment: dev
  type: ClusterIP
