# kustomization.yaml dev
---
resources:
- ../base
# Overrise base common labels
commonLabels:
  environment: dev

namespace: go-app
nameSuffix: -dev

images: 
- name: joellgarcia/hello-world-go
  newTag: 1.0.0

replicas:
- name: hello-world-go
  count: 2
