apiVersion: apps/v1
kind: Deployment
metadata: 
  name: hello-world-go
spec:
  selector: 
    matchLabels:
      app: hello-world-go
  template:
    metadata:
      labels:
        app: hello-world-go
    spec: 
      containers:
      - name: hello-world-go
        image: joellgarcia/hello-world-go
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
