apiVersion: apps/v1
kind: Deployment
metadata: # metadados sobre o pod, informações internas do cluster
  name: demo-app # nome interno do pod
spec:
  selector: 
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec: 
      containers:
      - name: demo-app
        image: julialamenza/api
        ports:
        - name: http
          containerPort: 8075
          protocol: TCP