---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-go-svc
spec:
  selector:
    app: hello-world-go
  ports:
    - name: http
      protocol: TCP 
      port: 80
      targetPort: 8080
  type: ClusterIP
