---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-svc
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-size-slug: "lb-small"
spec:
  selector:
    app: demo-app
  ports:
    - name: http
      protocol: TCP 
      port: 8075
      targetPort: 8075
  type: LoadBalancer