apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: go-app

commonLabels: 
  environment: base 

images: 
- name: joellgarcia/hello-world-go
  newTag: 1.0.0

replicas:
- name: hello-world-go
  count: 1

resources:
  - app/service.yaml
  - app/deployment.yaml
  - namespaces/namespace.yaml
