apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo

commonLabels: 
  environment: base 

images: 
- name: app
  newTag: '0.1.0'

replicas:
- name: demo-app
  count: 1


resources:
  - app/service.yaml
  - app/deployment.yaml
  - namespaces/namespace.yaml
